accelerate launch --multi_gpu --main_process_port 29501 /data/home/saividyaranya/PRISM/models/infer_trinity_sd15_pl3.py \
  --pretrained_model_name_or_path="stable-diffusion-v1-5/stable-diffusion-v1-5" \
  --dataset_name="/data/home/saividyaranya/PRISM/cached_folder_real/images_again/" \
  --output_dir="/home/saividyaranya/PRISM/all_output_logs/sdxl15_12_translayers" \
  --cache_dir="/data/home/saividyaranya/PRISM/model_weights/" \
  --bg_dir="/data/home/saividyaranya/PRISM/backgrounds" \
  --backup="/data/home/saividyaranya/PRISM/backup/" \
  --output_img_dir="/home/saividyaranya/PRISM/all_output_logs/sdxl15_infer_images3_8layers" \
  --resume_from_checkpoint="latest" \
  --wanna_bg=1 \
  --do_valid="True" \
  --valid_path_name="/data/home/saividyaranya/PRISM/validation/" \
  --caption_column="prompt" \
  --object_column="object" \
  --mask_typ="no_mask" \
  --blocks=8 \
  --mixed_precision="fp16" \
  --train_batch_size=2 \
  --snr_gamma=5.0 \
  --resolution=1024 \
  --lr_scheduler="cosine" \
  --lr_warmup_steps=0 \
  --use_8bit_adam \
  --num_train_epochs=40 \
  --checkpointing_steps=100 \
  --rank=16
