 accelerate launch --config_file /home/saividyaranya/PRISM/accelerate_config.yaml  --multi_gpu   /data/home/saividyaranya/PRISM/models/train_trinity_sd15_pl3.py \
  --pretrained_model_name_or_path="stable-diffusion-v1-5/stable-diffusion-v1-5" \
  --dataset_name="/data/home/saividyaranya/PRISM/cached_folder_real/images_again/" \
  --output_dir="/data/home/saividyaranya/PRISM/all_output_logs/sdxl15_12_translayers" \
  --cache_dir="/data/home/saividyaranya/PRISM/model_weights3/" \
  --bg_dir="/home/saividyaranya/PRISM/backgrounds/" \
  --backup="/home/saividyaranya/PRISM/backup/" \
  --wanna_bg=1 \
  --do_valid="True" \
  --valid_path_name="/nfshomes/asarkar6/aditya/PRISM/validation/" \
  --caption_column="prompt" \
  --object_column="object" \
  --mask_typ="no_mask" \
  --blocks=8 \
  --mixed_precision="fp16" \
  --train_batch_size=2 \
  --snr_gamma=5.0 \
  --resolution=1024 \
  --lr_scheduler="cosine" \
  --lr_warmup_steps=0 \
  --use_8bit_adam \
  --num_train_epochs=40 \
  --checkpointing_steps=1000 \
  --rank=16
