export MODEL_DIR="stable-diffusion-v1-5/stable-diffusion-v1-5"

accelerate launch --mixed_precision="fp16" --multi_gpu --main_process_port 29501 /data/home/saividyaranya/PRISM//models/train_trinity_controlnet.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
  --dataset_name="/data/home/saividyaranya/PRISM/cached_folder_real/images_again/" \
  --output_dir="/data/home/saividyaranya/PRISM/all_output_logs/sdxl15" \
  --cache_dir="/data/home/saividyaranya/PRISM/model_weights3/" \
  --bg_dir="/home/saividyaranya/PRISM/backgrounds/" \
  --backup="/home/saividyaranya/PRISM/backup/" \
 --wanna_bg=1 \
 --resume_from_checkpoint="latest" \
 --resolution=512 \
 --learning_rate=1e-5 \
 --train_batch_size=2 \
 --lr_scheduler="cosine" \
 --mixed_precision="fp16" \
 --num_train_epochs=40 \
 --checkpointing_steps=500 \
 --mixed_precision="fp16"