accelerate launch --multi_gpu /home/saividyaranya/PRISM/models/train_trinity_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
  --dataset_name="/data/home/saividyaranya/PRISM/cached_folder_real/images_again/" \
  --output_dir="/home/saividyaranya/PRISM/real_output/" \
  --cache_dir="/home/saividyaranya/PRISM/real_output/cache_dir/" \
  --caption_column="prompt" \
  --object_column="object" \
  --mask_typ="causal" \
  --blocks=4 \
  --mixed_precision="fp16" \
  --train_batch_size=1 \
  --snr_gamma=5.0 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --use_8bit_adam \
  --num_train_epochs=4 \
  --checkpointing_steps=100 \
  --seed="0"
