 accelerate launch --config_file /home/saividyaranya/PRISM/accelerate_config.yaml  --multi_gpu  /home/saividyaranya/PRISM/models/train_trinity_pixart_pl3.py \
  --pretrained_model_name_or_path="PixArt-alpha/PixArt-XL-2-1024-MS" \
  --dataset_name="/data/home/saividyaranya/PRISM/cached_folder_real/images_again/" \
  --output_dir="/data/home/saividyaranya/PRISM/all_output_logs/pixart3" \
  --cache_dir="/data/home/saividyaranya/PRISM/model_weights3/" \
  --bg_dir="/home/saividyaranya/PRISM/backgrounds/" \
  --backup="/home/saividyaranya/PRISM/backup/" \
  --resume_from_checkpoint="latest" \
  --wanna_bg=1 \
  --caption_column="prompt" \
  --resolution=1024 \
  --random_flip \
  --train_batch_size=2 \
  --num_train_epochs=40 \
  --checkpointing_steps=100 \
  --learning_rate=1e-06 \
  --mixed_precision="fp16" \
  --lr_scheduler="cosine" \
  --lr_warmup_steps=0 \
  --mask_typ="causal" \
  --blocks=4 \
  --seed=42 \
  --gradient_checkpointing \
  --rank=16