accelerate launch --multi_gpu /nfshomes/asarkar6/aditya/PRISM/models/train_trinity_pixart.py \
  --pretrained_model_name_or_path="PixArt-alpha/PixArt-XL-2-1024-MS" \
  --dataset_name="/nfshomes/asarkar6/trinity/train_data/" \
  --output_dir="/nfshomes/asarkar6/scratch/test_image/" \
  --cache_dir="/nfshomes/asarkar6/trinity/model_weights/" \
  --caption_column="prompt" \
  --resolution=1024 \
  --random_flip \
  --train_batch_size=1 \
  --num_train_epochs=4 \
  --checkpointing_steps=100 \
  --learning_rate=1e-06 \
  --mixed_precision="fp16" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --mask_typ="causal" \
  --blocks=4 \
  --seed=42 \
  --gradient_checkpointing \
  --rank=16